<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-05-01 13:06
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 13:16
from __future__ import unicode_literals
>>>>>>> 24e18e1ef48f821d2890c2db4072384567c5ddb4

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('batch', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('credit_struct', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_year', models.IntegerField()),
                ('current_sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateto', models.DateField()),
                ('datefrom', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='dean_staff_office',
            fields=[
                ('staff_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
                ('dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.department')),
            ],
        ),
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateto', models.DateField()),
                ('datefrom', models.DateField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateto', models.DateField()),
                ('datefrom', models.DateField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.faculty')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.dean_staff_office')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
<<<<<<< HEAD
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('curr_registered_credits', models.IntegerField()),
                ('max_credit', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('current_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('current_sem', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('password', models.CharField(max_length=12)),
=======
                ('cgpa', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('curr_registered_credits', models.IntegerField(default=0)),
                ('max_credit', models.IntegerField(default=24)),
                ('total_credits', models.IntegerField(default=0)),
                ('current_year', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('current_sem', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('password', models.CharField(default='abcdefgh', max_length=50)),
                ('student_email', models.CharField(default='', max_length=100)),
>>>>>>> 24e18e1ef48f821d2890c2db4072384567c5ddb4
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.department')),
            ],
        ),
        migrations.CreateModel(
            name='successfull_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.student')),
            ],
        ),
        migrations.CreateModel(
            name='takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.student')),
            ],
        ),
        migrations.CreateModel(
            name='teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField()),
                ('slot', models.CharField(max_length=2)),
                ('min_cgpa_constraint', models.DecimalField(decimal_places=2, max_digits=3)),
                ('batch', models.ManyToManyField(to='studentportal.batch')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.course')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.faculty')),
                ('prerequisite', models.ManyToManyField(related_name='prerequisites', to='studentportal.course')),
            ],
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('status', models.TextField()),
=======
                ('status', models.IntegerField()),
                ('reason', models.TextField(default=':and:')),
>>>>>>> 24e18e1ef48f821d2890c2db4072384567c5ddb4
                ('student_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.student')),
                ('teaches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.teaches')),
            ],
        ),
        migrations.AddField(
            model_name='takes',
            name='teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.teaches'),
        ),
        migrations.AddField(
            model_name='successfull_register',
            name='teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.teaches'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.student'),
        ),
        migrations.AddField(
            model_name='grades',
            name='teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.teaches'),
        ),
        migrations.AddField(
            model_name='dean',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.department'),
        ),
        migrations.AddField(
            model_name='batch',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.department'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='token',
<<<<<<< HEAD
            unique_together={('student_obj', 'teaches')},
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('faculty_id', 'course_id', 'semester', 'year', 'slot')},
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('student_obj', 'teaches')},
=======
            unique_together=set([('student_obj', 'teaches')]),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together=set([('faculty_id', 'course_id', 'semester', 'year', 'slot')]),
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together=set([('student_obj', 'teaches')]),
>>>>>>> 24e18e1ef48f821d2890c2db4072384567c5ddb4
        ),
        migrations.AlterUniqueTogether(
            name='successfull_register',
            unique_together={('student_id', 'teaches')},
        ),
        migrations.AlterUniqueTogether(
            name='related',
            unique_together={('staff_id', 'dateto', 'datefrom')},
        ),
        migrations.AlterUniqueTogether(
            name='hod',
            unique_together={('dateto', 'datefrom', 'faculty_id')},
        ),
        migrations.AlterUniqueTogether(
            name='dean',
            unique_together={('dateto', 'datefrom', 'faculty_id')},
        ),
        migrations.AlterUniqueTogether(
            name='advisor',
            unique_together={('faculty_id', 'year')},
        ),
    ]
