# Generated by Django 2.0.4 on 2018-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='dateto',
            field=models.DateField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='hod',
            unique_together={('datefrom', 'faculty_id')},
        ),
    ]
