# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='section',
        ),
        migrations.AlterField(
            model_name='current',
            name='current_sem',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='current',
            name='current_year',
            field=models.IntegerField(default=2018),
        ),
    ]
