# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takes',
            old_name='student_id',
            new_name='student_obj',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='student_id',
            new_name='student_obj',
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together=set([('student_obj', 'teaches')]),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('student_obj', 'teaches')]),
        ),
    ]
