# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='portalsOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp_open', models.BooleanField(default=False)),
                ('grade_update_open', models.BooleanField(default=False)),
            ],
        ),
    ]
