# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
