# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(),
        ),
    ]
