# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 10:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_auto_20180430_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='curr_registered_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='max_credit',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='abcdefgh', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_credits',
            field=models.IntegerField(default=0),
        ),
    ]
