# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 16:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0002_auto_20180429_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentportal.department')),
            ],
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='department',
        ),
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RemoveField(
            model_name='teaches',
            name='batch',
        ),
        migrations.AddField(
            model_name='teaches',
            name='batch',
            field=models.ManyToManyField(to='studentportal.batch'),
        ),
    ]
