# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0003_auto_20180501_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaches',
            name='section_id',
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
