# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 00:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentportal', '0003_auto_20180429_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.TextField(),
        ),
    ]
